# Generated by Django 3.2.4 on 2021-09-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_ordermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='canteen',
            field=models.ManyToManyField(related_name='item1', to='customer.CanteenList'),
        ),
    ]
