# Generated by Django 3.2.4 on 2021-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_menuitem_canteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='availability',
            field=models.ManyToManyField(related_name='item2', to='customer.Availability'),
        ),
    ]
