# Generated by Django 3.2.4 on 2021-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210921_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='availability',
            field=models.ManyToManyField(related_name='item', to='customer.Availability'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='canteen',
            field=models.ManyToManyField(related_name='item', to='customer.CanteenList'),
        ),
    ]
