# Generated by Django 3.2.4 on 2021-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210921_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='canteen',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='availability',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
