# Generated by Django 3.2.4 on 2021-09-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20210922_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='street',
        ),
    ]
