# Generated by Django 3.2.4 on 2021-09-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210923_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='canteen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.canteenlist'),
        ),
    ]
