# Generated by Django 3.2.4 on 2021-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenlist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
