# Generated by Django 3.2.4 on 2021-09-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_canteenlist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
