# Generated by Django 3.2.4 on 2021-09-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='canteen',
        ),
    ]
