# Generated by Django 3.2.4 on 2021-09-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_remove_menuitem_canteen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='canteen',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='canteen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.canteenlist'),
        ),
    ]
